-- =============================================================================
-- 02_datos_iniciales.sql
-- Carga los registros base de las tablas area_conocimiento (218) y universidad (6).
-- Es idempotente: primero borra los datos de las dos tablas y los reinserta.
-- Fuente: docs/spec_kit/versiones/v1_producto_sqlserver/5_data_model.md, Seccion 4.
-- =============================================================================
USE [innovacion_curricular];
GO

DELETE FROM area_conocimiento;
DELETE FROM universidad;
GO

INSERT INTO area_conocimiento (id, gran_area, area, disciplina) VALUES
(1, N'Ciencias Naturales', N'Matematicas', N'Matematica Aplicada'),
(2, N'Ciencias Naturales', N'Matematicas', N'Matematica Pura'),
(3, N'Ciencias Naturales', N'Matematicas', N'Estadistica'),
(4, N'Ciencias Naturales', N'Matematicas', N'Actuaria'),
(5, N'Ciencias Naturales', N'Matematicas', N'Analisis Numerico'),
(6, N'Ciencias Naturales', N'Matematicas', N'Algebra'),
(7, N'Ciencias Naturales', N'Matematicas', N'Geometria'),
(8, N'Ciencias Naturales', N'Matematicas', N'Topologia'),
(9, N'Ciencias Naturales', N'Matematicas', N'Probabilidad'),
(10, N'Ciencias Naturales', N'Matematicas', N'Teoria de Numeros'),
(11, N'Ciencias Naturales', N'Matematicas', N'Logica Matematica'),
(12, N'Ciencias Naturales', N'Matematicas', N'Calculo'),
(13, N'Ciencias Naturales', N'Fisica', N'Fisica General'),
(14, N'Ciencias Naturales', N'Fisica', N'Fisica Atomica y Molecular'),
(15, N'Ciencias Naturales', N'Fisica', N'Fisica Nuclear'),
(16, N'Ciencias Naturales', N'Fisica', N'Astronomia'),
(17, N'Ciencias Naturales', N'Fisica', N'Astrofisica'),
(18, N'Ciencias Naturales', N'Fisica', N'Fisica Teorica'),
(19, N'Ciencias Naturales', N'Fisica', N'Optica'),
(20, N'Ciencias Naturales', N'Fisica', N'Electromagnetismo'),
(21, N'Ciencias Naturales', N'Fisica', N'Mecanica Clasica'),
(22, N'Ciencias Naturales', N'Fisica', N'Termodinamica'),
(23, N'Ciencias Naturales', N'Fisica', N'Fisica de Materiales'),
(24, N'Ciencias Naturales', N'Fisica', N'Fisica Medica'),
(25, N'Ciencias Naturales', N'Quimica', N'Quimica General'),
(26, N'Ciencias Naturales', N'Quimica', N'Quimica Organica'),
(27, N'Ciencias Naturales', N'Quimica', N'Quimica Inorganica'),
(28, N'Ciencias Naturales', N'Quimica', N'Quimica Analitica'),
(29, N'Ciencias Naturales', N'Quimica', N'Fisicoquimica'),
(30, N'Ciencias Naturales', N'Quimica', N'Bioquimica'),
(31, N'Ciencias Naturales', N'Quimica', N'Quimica Ambiental'),
(32, N'Ciencias Naturales', N'Quimica', N'Petroquimica'),
(33, N'Ciencias Naturales', N'Quimica', N'Quimica Farmaceutica'),
(34, N'Ciencias Naturales', N'Quimica', N'Quimica de Alimentos'),
(35, N'Ciencias Naturales', N'Biologia', N'Biologia General'),
(36, N'Ciencias Naturales', N'Biologia', N'Botanica'),
(37, N'Ciencias Naturales', N'Biologia', N'Zoologia'),
(38, N'Ciencias Naturales', N'Biologia', N'Ecologia'),
(39, N'Ciencias Naturales', N'Biologia', N'Genetica'),
(40, N'Ciencias Naturales', N'Biologia', N'Microbiologia'),
(41, N'Ciencias Naturales', N'Biologia', N'Biologia Marina'),
(42, N'Ciencias Naturales', N'Biologia', N'Biologia Molecular'),
(43, N'Ciencias Naturales', N'Biologia', N'Entomologia'),
(44, N'Ciencias Naturales', N'Biologia', N'Parasitologia'),
(45, N'Ciencias Naturales', N'Biologia', N'Biotecnologia'),
(46, N'Ciencias Naturales', N'Biologia', N'Conservacion Biologica'),
(47, N'Ciencias Naturales', N'Ciencias de la Tierra', N'Geologia'),
(48, N'Ciencias Naturales', N'Ciencias de la Tierra', N'Geografia'),
(49, N'Ciencias Naturales', N'Ciencias de la Tierra', N'Oceanografia'),
(50, N'Ciencias Naturales', N'Ciencias de la Tierra', N'Meteorologia'),
(51, N'Ciencias Naturales', N'Ciencias de la Tierra', N'Hidrologia'),
(52, N'Ciencias Naturales', N'Ciencias de la Tierra', N'Sismologia'),
(53, N'Ciencias Naturales', N'Ciencias de la Tierra', N'Vulcanologia'),
(54, N'Ciencias Naturales', N'Ciencias de la Tierra', N'Paleontologia'),
(55, N'Ciencias Naturales', N'Ciencias de la Tierra', N'Edafologia'),
(56, N'Ciencias Naturales', N'Ciencias de la Tierra', N'Glaciologia'),
(57, N'Ciencias Naturales', N'Estadistica', N'Estadistica Aplicada'),
(58, N'Ciencias Naturales', N'Estadistica', N'Estadistica Matematica'),
(59, N'Ciencias Naturales', N'Estadistica', N'Bioestadistica'),
(60, N'Ciencias Naturales', N'Estadistica', N'Estadistica Computacional'),
(61, N'Ciencias Naturales', N'Estadistica', N'Estadistica Economica'),
(62, N'Ciencias Naturales', N'Estadistica', N'Demografia'),
(63, N'Ingenieria y Tecnologia', N'Ingenieria de Sistemas', N'Computacion'),
(64, N'Ingenieria y Tecnologia', N'Ingenieria de Sistemas', N'Desarrollo de Software'),
(65, N'Ingenieria y Tecnologia', N'Ingenieria de Sistemas', N'Ingenieria de Software'),
(66, N'Ingenieria y Tecnologia', N'Ingenieria de Sistemas', N'Seguridad Informatica'),
(67, N'Ingenieria y Tecnologia', N'Ingenieria de Sistemas', N'Ciencia de Datos'),
(68, N'Ingenieria y Tecnologia', N'Ingenieria de Sistemas', N'Inteligencia Artificial'),
(69, N'Ingenieria y Tecnologia', N'Ingenieria de Sistemas', N'Redes de Computadores'),
(70, N'Ingenieria y Tecnologia', N'Ingenieria de Sistemas', N'Sistemas Distribuidos'),
(71, N'Ingenieria y Tecnologia', N'Ingenieria de Sistemas', N'Arquitectura de Software'),
(72, N'Ingenieria y Tecnologia', N'Ingenieria de Sistemas', N'Bases de Datos'),
(73, N'Ingenieria y Tecnologia', N'Ingenieria Electronica', N'Electronica Analoga'),
(74, N'Ingenieria y Tecnologia', N'Ingenieria Electronica', N'Electronica Digital'),
(75, N'Ingenieria y Tecnologia', N'Ingenieria Electronica', N'Telecomunicaciones'),
(76, N'Ingenieria y Tecnologia', N'Ingenieria Electronica', N'Automatizacion Industrial'),
(77, N'Ingenieria y Tecnologia', N'Ingenieria Electronica', N'Instrumentacion'),
(78, N'Ingenieria y Tecnologia', N'Ingenieria Electronica', N'Sistemas Embebidos'),
(79, N'Ingenieria y Tecnologia', N'Ingenieria Electronica', N'Robotica'),
(80, N'Ingenieria y Tecnologia', N'Ingenieria Electronica', N'Control Automatico'),
(81, N'Ingenieria y Tecnologia', N'Ingenieria Electronica', N'Microelectronica'),
(82, N'Ingenieria y Tecnologia', N'Ingenieria Electronica', N'Sistemas de Potencia'),
(83, N'Ingenieria y Tecnologia', N'Ingenieria Electrica', N'Sistemas Electricos de Potencia'),
(84, N'Ingenieria y Tecnologia', N'Ingenieria Electrica', N'Maquinas Electricas'),
(85, N'Ingenieria y Tecnologia', N'Ingenieria Electrica', N'Electronica de Potencia'),
(86, N'Ingenieria y Tecnologia', N'Ingenieria Electrica', N'Distribucion Electrica'),
(87, N'Ingenieria y Tecnologia', N'Ingenieria Electrica', N'Generacion de Energia'),
(88, N'Ingenieria y Tecnologia', N'Ingenieria Electrica', N'Iluminacion'),
(89, N'Ingenieria y Tecnologia', N'Ingenieria Electrica', N'Redes Inteligentes'),
(90, N'Ingenieria y Tecnologia', N'Ingenieria Electrica', N'Mantenimiento Electrico'),
(91, N'Ingenieria y Tecnologia', N'Ingenieria Mecanica', N'Diseno Mecanico'),
(92, N'Ingenieria y Tecnologia', N'Ingenieria Mecanica', N'Termofluidos'),
(93, N'Ingenieria y Tecnologia', N'Ingenieria Mecanica', N'Ciencia de Materiales'),
(94, N'Ingenieria y Tecnologia', N'Ingenieria Mecanica', N'Manufactura'),
(95, N'Ingenieria y Tecnologia', N'Ingenieria Mecanica', N'Mecatronica'),
(96, N'Ingenieria y Tecnologia', N'Ingenieria Mecanica', N'Energias Renovables'),
(97, N'Ingenieria y Tecnologia', N'Ingenieria Mecanica', N'Mecanica de Fluidos'),
(98, N'Ingenieria y Tecnologia', N'Ingenieria Mecanica', N'Transferencia de Calor'),
(99, N'Ingenieria y Tecnologia', N'Ingenieria Mecanica', N'Vibraciones Mecanicas'),
(100, N'Ingenieria y Tecnologia', N'Ingenieria Civil', N'Estructuras'),
(101, N'Ingenieria y Tecnologia', N'Ingenieria Civil', N'Geotecnia'),
(102, N'Ingenieria y Tecnologia', N'Ingenieria Civil', N'Vias y Transporte'),
(103, N'Ingenieria y Tecnologia', N'Ingenieria Civil', N'Hidraulica'),
(104, N'Ingenieria y Tecnologia', N'Ingenieria Civil', N'Construccion'),
(105, N'Ingenieria y Tecnologia', N'Ingenieria Civil', N'Ingenieria Sanitaria'),
(106, N'Ingenieria y Tecnologia', N'Ingenieria Civil', N'Materiales de Construccion'),
(107, N'Ingenieria y Tecnologia', N'Ingenieria Civil', N'Topografia'),
(108, N'Ingenieria y Tecnologia', N'Ingenieria Civil', N'Edificaciones'),
(109, N'Ingenieria y Tecnologia', N'Ingenieria Quimica', N'Procesos Quimicos'),
(110, N'Ingenieria y Tecnologia', N'Ingenieria Quimica', N'Fenomenos de Transferencia'),
(111, N'Ingenieria y Tecnologia', N'Ingenieria Quimica', N'Control de Procesos'),
(112, N'Ingenieria y Tecnologia', N'Ingenieria Quimica', N'Bioprocesos'),
(113, N'Ingenieria y Tecnologia', N'Ingenieria Quimica', N'Refinacion'),
(114, N'Ingenieria y Tecnologia', N'Ingenieria Quimica', N'Polimeros'),
(115, N'Ingenieria y Tecnologia', N'Ingenieria Quimica', N'Catalisis'),
(116, N'Ingenieria y Tecnologia', N'Ingenieria Quimica', N'Ingenieria de Alimentos'),
(117, N'Ingenieria y Tecnologia', N'Ingenieria Quimica', N'Diseno de Plantas'),
(118, N'Ingenieria y Tecnologia', N'Ingenieria Quimica', N'Seguridad Industrial'),
(119, N'Ingenieria y Tecnologia', N'Ingenieria Industrial', N'Gestion de Operaciones'),
(120, N'Ingenieria y Tecnologia', N'Ingenieria Industrial', N'Logistica'),
(121, N'Ingenieria y Tecnologia', N'Ingenieria Industrial', N'Optimizacion de Procesos'),
(122, N'Ingenieria y Tecnologia', N'Ingenieria Industrial', N'Gestion de Calidad'),
(123, N'Ingenieria y Tecnologia', N'Ingenieria Industrial', N'Planeacion de Produccion'),
(124, N'Ingenieria y Tecnologia', N'Ingenieria Industrial', N'Seguridad y Salud en el Trabajo'),
(125, N'Ingenieria y Tecnologia', N'Ingenieria Industrial', N'Gestion de Proyectos'),
(126, N'Ingenieria y Tecnologia', N'Ingenieria Industrial', N'Ingenieria Economica'),
(127, N'Ingenieria y Tecnologia', N'Ingenieria Industrial', N'Ergonomia'),
(128, N'Ingenieria y Tecnologia', N'Ingenieria Industrial', N'Gerencia de Procesos'),
(129, N'Ingenieria y Tecnologia', N'Ingenieria Ambiental', N'Tratamiento de Aguas'),
(130, N'Ingenieria y Tecnologia', N'Ingenieria Ambiental', N'Gestion Ambiental'),
(131, N'Ingenieria y Tecnologia', N'Ingenieria Ambiental', N'Modelacion Ambiental'),
(132, N'Ingenieria y Tecnologia', N'Ingenieria Ambiental', N'Impacto Ambiental'),
(133, N'Ingenieria y Tecnologia', N'Ingenieria Ambiental', N'Residuos Solidos'),
(134, N'Ingenieria y Tecnologia', N'Ingenieria Ambiental', N'Contaminacion Atmosferica'),
(135, N'Ingenieria y Tecnologia', N'Ingenieria Ambiental', N'Energias Limpias'),
(136, N'Ingenieria y Tecnologia', N'Ingenieria Ambiental', N'Educacion Ambiental'),
(137, N'Ingenieria y Tecnologia', N'Ingenieria Ambiental', N'Ecoeficiencia'),
(138, N'Ciencias Sociales y Humanas', N'Derecho', N'Derecho Publico'),
(139, N'Ciencias Sociales y Humanas', N'Derecho', N'Derecho Privado'),
(140, N'Ciencias Sociales y Humanas', N'Derecho', N'Derecho Penal'),
(141, N'Ciencias Sociales y Humanas', N'Derecho', N'Derecho Laboral'),
(142, N'Ciencias Sociales y Humanas', N'Derecho', N'Derecho Constitucional'),
(143, N'Ciencias Sociales y Humanas', N'Derecho', N'Derecho Administrativo'),
(144, N'Ciencias Sociales y Humanas', N'Derecho', N'Derecho Comercial'),
(145, N'Ciencias Sociales y Humanas', N'Derecho', N'Derecho Internacional'),
(146, N'Ciencias Sociales y Humanas', N'Derecho', N'Derechos Humanos'),
(147, N'Ciencias Sociales y Humanas', N'Derecho', N'Derecho Ambiental'),
(148, N'Ciencias Sociales y Humanas', N'Ciencias Politicas', N'Gobierno y Politicas Publicas'),
(149, N'Ciencias Sociales y Humanas', N'Ciencias Politicas', N'Relaciones Internacionales'),
(150, N'Ciencias Sociales y Humanas', N'Ciencias Politicas', N'Geopolitica'),
(151, N'Ciencias Sociales y Humanas', N'Ciencias Politicas', N'Administracion Publica'),
(152, N'Ciencias Sociales y Humanas', N'Ciencias Politicas', N'Teoria Politica'),
(153, N'Ciencias Sociales y Humanas', N'Ciencias Politicas', N'Cooperacion Internacional'),
(154, N'Ciencias Sociales y Humanas', N'Ciencias Politicas', N'Seguridad y Defensa'),
(155, N'Ciencias Sociales y Humanas', N'Sociologia', N'Sociologia General'),
(156, N'Ciencias Sociales y Humanas', N'Sociologia', N'Sociologia Urbana'),
(157, N'Ciencias Sociales y Humanas', N'Sociologia', N'Sociologia Rural'),
(158, N'Ciencias Sociales y Humanas', N'Sociologia', N'Sociologia de la Educacion'),
(159, N'Ciencias Sociales y Humanas', N'Sociologia', N'Sociologia del Trabajo'),
(160, N'Ciencias Sociales y Humanas', N'Sociologia', N'Demografia Social'),
(161, N'Ciencias Sociales y Humanas', N'Sociologia', N'Estudios Culturales'),
(162, N'Ciencias Sociales y Humanas', N'Psicologia', N'Psicologia Clinica'),
(163, N'Ciencias Sociales y Humanas', N'Psicologia', N'Psicologia Educativa'),
(164, N'Ciencias Sociales y Humanas', N'Psicologia', N'Psicologia Organizacional'),
(165, N'Ciencias Sociales y Humanas', N'Psicologia', N'Psicologia Social'),
(166, N'Ciencias Sociales y Humanas', N'Psicologia', N'Neuropsicologia'),
(167, N'Ciencias Sociales y Humanas', N'Psicologia', N'Psicologia Infantil'),
(168, N'Ciencias Sociales y Humanas', N'Psicologia', N'Psicometria'),
(169, N'Ciencias Sociales y Humanas', N'Psicologia', N'Psicologia Comunitaria'),
(170, N'Ciencias Sociales y Humanas', N'Periodismo e Informacion', N'Periodismo'),
(171, N'Ciencias Sociales y Humanas', N'Periodismo e Informacion', N'Comunicacion Social'),
(172, N'Ciencias Sociales y Humanas', N'Periodismo e Informacion', N'Comunicacion Audiovisual'),
(173, N'Ciencias Sociales y Humanas', N'Periodismo e Informacion', N'Comunicacion Digital'),
(174, N'Ciencias Sociales y Humanas', N'Periodismo e Informacion', N'Comunicacion Corporativa'),
(175, N'Ciencias Sociales y Humanas', N'Periodismo e Informacion', N'Publicidad'),
(176, N'Ciencias Sociales y Humanas', N'Economia', N'Economia General'),
(177, N'Ciencias Sociales y Humanas', N'Economia', N'Microeconomia'),
(178, N'Ciencias Sociales y Humanas', N'Economia', N'Macroeconomia'),
(179, N'Ciencias Sociales y Humanas', N'Economia', N'Econometria'),
(180, N'Ciencias Sociales y Humanas', N'Economia', N'Economia Internacional'),
(181, N'Ciencias Sociales y Humanas', N'Economia', N'Economia Publica'),
(182, N'Ciencias Sociales y Humanas', N'Economia', N'Desarrollo Economico'),
(183, N'Ciencias Sociales y Humanas', N'Economia', N'Economia Laboral'),
(184, N'Ciencias Sociales y Humanas', N'Administracion', N'Administracion General'),
(185, N'Ciencias Sociales y Humanas', N'Administracion', N'Gestion del Talento Humano'),
(186, N'Ciencias Sociales y Humanas', N'Administracion', N'Mercadeo'),
(187, N'Ciencias Sociales y Humanas', N'Administracion', N'Finanzas'),
(188, N'Ciencias Sociales y Humanas', N'Administracion', N'Contabilidad'),
(189, N'Ciencias Sociales y Humanas', N'Administracion', N'Auditoria'),
(190, N'Ciencias Sociales y Humanas', N'Administracion', N'Gestion de Operaciones'),
(191, N'Ciencias Sociales y Humanas', N'Administracion', N'Emprendimiento'),
(192, N'Ciencias Sociales y Humanas', N'Administracion', N'Gerencia de Servicios'),
(193, N'Ciencias de la Salud', N'Medicina', N'Medicina General'),
(194, N'Ciencias de la Salud', N'Medicina', N'Medicina Interna'),
(195, N'Ciencias de la Salud', N'Medicina', N'Pediatria'),
(196, N'Ciencias de la Salud', N'Medicina', N'Ginecologia y Obstetricia'),
(197, N'Ciencias de la Salud', N'Medicina', N'Cirugia General'),
(198, N'Ciencias de la Salud', N'Medicina', N'Medicina Familiar'),
(199, N'Ciencias de la Salud', N'Medicina', N'Psiquiatria'),
(200, N'Ciencias de la Salud', N'Medicina', N'Traumatologia'),
(201, N'Ciencias de la Salud', N'Medicina', N'Cardiologia'),
(202, N'Ciencias de la Salud', N'Medicina', N'Dermatologia'),
(203, N'Ciencias de la Salud', N'Odontologia', N'Odontologia General'),
(204, N'Ciencias de la Salud', N'Odontologia', N'Ortodoncia'),
(205, N'Ciencias de la Salud', N'Odontologia', N'Endodoncia'),
(206, N'Ciencias de la Salud', N'Odontologia', N'Periodoncia'),
(207, N'Ciencias de la Salud', N'Odontologia', N'Odontopediatria'),
(208, N'Ciencias de la Salud', N'Odontologia', N'Cirugia Oral'),
(209, N'Ciencias de la Salud', N'Odontologia', N'Rehabilitacion Oral'),
(210, N'Ciencias de la Salud', N'Enfermeria', N'Enfermeria General'),
(211, N'Ciencias de la Salud', N'Enfermeria', N'Enfermeria Clinica'),
(212, N'Ciencias de la Salud', N'Enfermeria', N'Enfermeria Comunitaria'),
(213, N'Ciencias de la Salud', N'Enfermeria', N'Enfermeria Quirurgica'),
(214, N'Ciencias de la Salud', N'Enfermeria', N'Cuidado Intensivo'),
(215, N'Ciencias de la Salud', N'Enfermeria', N'Enfermeria Pediatrica'),
(216, N'Ciencias de la Salud', N'Enfermeria', N'Etica en Enfermeria'),
(217, N'Ciencias de la Salud', N'Salud Publica', N'Epidemiologia'),
(218, N'Ciencias de la Salud', N'Salud Publica', N'Promocion de la Salud');

GO
-- 6 universidades base
INSERT INTO universidad (id, nombre, tipo, ciudad) VALUES
(1, N'Universidad Nacional de Colombia', N'Publica', N'Bogota'),
(2, N'Universidad de Antioquia', N'Publica', N'Medellin'),
(3, N'Universidad del Valle', N'Publica', N'Cali'),
(4, N'Universidad Industrial de Santander', N'Publica', N'Bucaramanga'),
(5, N'Universidad de los Andes', N'Privada', N'Bogota'),
(6, N'Universidad Pontificia Bolivariana', N'Privada', N'Medellin');
GO
